# We are fine with 120 character lines
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
